name: vprofile actions
on: workflow_dispatch
env:
  AWS_REGION: ap-southeast-1
  ECR_REPORSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Maven test
        run: mvn test
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
